(global-set-key [(hyper v)] 'yank)
(global-set-key [(hyper c)] 'kill-ring-save)
(setq mac-option-modifier 'meta)
(set-face-attribute 'default nil :height 150)
(set-face-attribute 'default nil :family "Terminus (TTF)")
