#!/usr/bin/sh


# Install Homebrew
if ! command -v brew &> /dev/null
then
    echo "Homebrew not installed"
    while true; do
    read -p "Do you wish to install this program?" yn
    case $yn in
        [Yy]* ) /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"; break;;
        [Nn]* ) break;;
        * ) echo "Please answer yes or no.";;
    esac
    done
fi


# Install iterm2

if [ "$(uname)" == "Darwin" ]; then
    echo "MacOS detected"
    while true; do
        read -p "Do you wish to install iterm2?" yn
        case $yn in
            [Yn]* ) brew install --cask iterm2; break;;
            [Nn]* ) break;;
            * ) echo "Please answer yes or no.";;
        esac
    done
fi

# Install powerlevel10k

git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
echo 'source ~/powerlevel10k/powerlevel10k.zsh-theme' >>~/.zshrc








# iterm2 Material Theme
curl -O https://raw.githubusercontent.com/MartinSeeler/iterm2-material-design/master/material-design-colors.itermcolors
